on:
 [push]

jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]

    env:
        LOGIN: ${{ secrets.DOCKER_LOGIN }}
        NAME: ${{ secrets.DOCKER_NAME }}

    steps:
      - name: Make config file
        run: ls
