on:
 [push]

jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]

    env:
        LOGIN: ${{ secrets.DOCKER_LOGIN }}
        NAME: ${{ secrets.DOCKER_NAME }}
        PWD: ${{ secrets.DOCKER_PWD }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGODB_URL: ${{ secrets.MONGODB_URL }}

    steps:
      - uses: actions/checkout@v2
      - name: Make config file
        working-directory: ${{ github.workspace }}/app
        run: |
            echo "BOT_TOKEN='$BOT_TOKEN'\nMONGODB_URL='$MONGODB_URL'" >> constants/config.py
      - name: Login to docker.io
        run:  echo $PWD | docker login -u $LOGIN --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build . --tag $NAME
      - name: Push image to docker.io
        run: docker push $NAME
