on:
 [push]

jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]

    env:
        LOGIN: ${{ secrets.DOCKER_LOGIN }}
        NAME: ${{ secrets.DOCKER_NAME }}

    steps:
      - name: Make config file
        run: echo "BOT_TOKEN='${{ secrets.BOT_TOKEN }}'\nMONGODB_URL='${{ secrets.MONGODB_URL }}'" > ./app/constants/config.py
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}
