on:
 [push]

jobs:
  build_and_pub:
    runs-on: [ubuntu-latest]

    env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        MONGODB_URL: ${{ secrets.MONGODB_URL }}

    steps:
      - uses: actions/checkout@v2
      - name: Make config file
        run: |
            echo "BOT_TOKEN='$BOT_TOKEN'\nMONGODB_URL='$MONGODB_URL'" >> app/constants/config.py
            cat app/constants/config.py
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PWD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_NAME }}
